config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  get 'tasks/show'
  get 'tasks/new'
  get 'tasks/edit'
  root 'boards#index'

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:edit, :destroy, :update, :show]
  
    def index
      @boards = Board.all
    end
  
    def show
    end
  
    def new
      @board = Board.new
      render partial: "form"
    end
  
    def edit
      render partial: "form"
    end
  
    def create
      @board = Board.new(board_params)
      
      if @board.save
        redirect_to boards_path
      else
        render :new
      end
    end
  
    def update
      if @board.update(board_params)
        redirect_to @board
      else
        render :edit
      end
    end
  
    def destroy
      @board.destroy
      redirect_to boards_path
    end
  
    private
      
      def set_board
        @board = Board.find(params[:id])
      end
  
      def board_params
        params.require(:board).permit(:title)
      end
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = @board.lists
  end

  def show
  end

  def new
    @list = @board.lists.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to [@board, @list]
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to [@board, @list]
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path
  end

  private
    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :priority)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list

  def new
    @task = Task.new
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to board_list_path(@list.board_id, @list)
    else
      render :new
    end
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end

    def task_params
      params.require(:task).permit(:title, :body, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<h1><%= @board.id ? 'Edit Board' : 'Create Board' %></h1>
<hr />
<%= form_for [@board] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
 
  <%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<h1>Click a Board to view lists</h1>
<%= link_to 'Create a new board', new_board_path %>
<ul>
  <% @boards.each do |board| %>
    <li><%= link_to board.title, board %></li>
  <% end %>
</ul>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Lists', board_lists_path(@board) %>
<br />
<%= link_to 'Edit Board', edit_board_path(@board) %>
<br />
<%= link_to 'Delete Board', @board, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create List' %></h1>
<hr />
<%= form_for [@board, @list] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :priority %>
  <%= f.number_field :priority %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>Click a List To View Content</h1>
<%= link_to 'Create a new list', new_board_list_path(@board) %>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.title, [@board, list] %></li>
  <% end %>
</ul>

app/views/lists/show.html.erb
<h1><%= @board.title %></h1>
<h2><%= @list.title %></h2> <h2><%@list.priority %></h2>
<%= link_to 'Edit List', edit_board_list_path([@board, @list]) %>
<%= link_to 'Delete List', [@board, @list], method: :delete %>
<%= link_to 'Back To Lists', board_lists_path(@board) %>
<%= link_to 'Go To Tasks', list_tasks_path(@list)%>

app/views/tasks/_form.html.erb
<h1><%= @task.id ? 'Edit Task' : 'Create Task' %></h1>
<hr />
<%= form_for [@list, @task] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to 'Create a new task', new_list_task_path(@list) %>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, [@list, task] %></li>
  <% end %>
</ul>

app/views/tasks/show.html.erb
<h1><%= @board.title %></h1>
<h2><%= @list.title %></h2> <h2><%@list.priority %></h2>
<h3><%= @task.title %></h3>
<%= link_to 'Edit Task', edit_board_list_path([@list, @task]) %>
<%= link_to 'Delete Task', [@list, @task], method: :delete %>
<%= link_to 'Back To Lists', board_lists_path(@board) %>